'use client';

import Link from 'next/link';
import Card from '@/components/Card';
import ExplanationPanel from '@/components/ExplanationPanel';
import PressureBandChip from '@/components/PressureBandChip';
import StatCard from '@/components/StatCard';
import type {
  DashboardSummaryResponse,
  EstimatedContribution,
} from '@/types/api';

/**
 * Everything the authority dashboard shows (F8).
 *
 * Deliberately takes the summary as a prop and does no fetching and no auth of
 * its own. F8 says that if time runs short, a static summary with no login
 * still demonstrates the two-audience idea, and that the auth should be cut
 * before the dashboard. Keeping this component ignorant of how it got its data
 * means that fallback is always one line away: render it from any source and
 * the login disappears.
 */

/** How many rows of the hotspot table to show. */
const TABLE_ROWS = 5;

export default function DashboardContent({
  summary,
}: {
  summary: DashboardSummaryResponse;
}) {
  /**
   * The global importance figures, mapped onto the contribution shape so the
   * F3 panel can draw them.
   *
   * Every one is a mean absolute SHAP value — an estimate from the model, not
   * a measured quantity — so every bar comes out hatched, outlined and marked
   * `est.` without the panel needing to be told. That is the same distinction
   * the recommendation cards make, applied to the model as a whole.
   *
   * `importance` is a fraction of 1, so it scales to a percentage. The five
   * account for the whole model, which is why the total is 100.
   */
  const importanceBars: EstimatedContribution[] =
    summary.global_feature_importance.map((entry) => ({
      type: 'estimated',
      factor: entry.feature,
      percent: Math.round(entry.importance * 100),
    }));

  const topHotspots = summary.highest_pressure.slice(0, TABLE_ROWS);
  const mostPressured = topHotspots[0];

  return (
    <div className="space-y-4">
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        <StatCard
          label="Destinations monitored"
          value={summary.destinations_monitored}
        />
        <StatCard
          label="Low pressure"
          value={summary.band_counts.low}
          band="low"
        />
        <StatCard
          label="Medium pressure"
          value={summary.band_counts.medium}
          band="medium"
        />
        <StatCard
          label="High pressure"
          value={summary.band_counts.high}
          band="high"
        />
      </div>

      {/*
        F8: the recommended action, in a callout. It is the action for the
        most pressured destination, because that is the one an official has to
        deal with first. The sentence is generated by the API from the
        forecast — nothing here writes it.
      */}
      {mostPressured && (
        <div className="rounded-lg border-l-4 border-brand bg-brand-light p-4">
          <p className="text-xs font-semibold uppercase tracking-wide text-brand">
            Recommended action
          </p>
          <p className="mt-1 text-base leading-relaxed text-ink">
            {mostPressured.recommended_action}
          </p>
        </div>
      )}

      <Card
        title="Highest forecast pressure"
        subtitle="Pressure is a regional indicator, not a measurement for a single site."
      >
        {/* The table scrolls inside its own box rather than pushing the page
            sideways on a phone. */}
        <div className="-mx-1 overflow-x-auto">
          <table className="w-full min-w-[30rem] text-left text-sm">
            <thead>
              <tr className="border-b border-line text-xs uppercase tracking-wide text-muted">
                <th scope="col" className="px-1 py-2 font-medium">
                  Destination
                </th>
                <th scope="col" className="px-1 py-2 font-medium">
                  Region
                </th>
                <th scope="col" className="px-1 py-2 text-right font-medium">
                  Pressure
                </th>
                <th scope="col" className="px-1 py-2 font-medium">
                  Band
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-line">
              {topHotspots.map((hotspot) => (
                <tr key={hotspot.destination_id}>
                  <td className="px-1 py-2">
                    <Link
                      href={`/destination/${hotspot.destination_id}/risk`}
                      className="font-medium text-brand underline underline-offset-2"
                    >
                      {hotspot.name}
                    </Link>
                  </td>
                  <td className="px-1 py-2 text-muted">{hotspot.region}</td>
                  <td className="px-1 py-2 text-right tabular-nums text-ink">
                    {hotspot.predicted_pressure}%
                  </td>
                  <td className="px-1 py-2">
                    <PressureBandChip band={hotspot.band} size="sm" />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>

      <Card>
        {/*
          The same panel as a result card, the risk view and the simulator.
          Fourth caller, still one bar component.
        */}
        <ExplanationPanel
          heading="What drives the pressure forecast?"
          total={100}
          totalLabel="Model importance"
          contributions={importanceBars}
          explanation={summary.model_explanation}
        />
      </Card>
    </div>
  );
}
